name: k6_grafana

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./tmp/influxdb:/var/lib/influxdb2
    restart: on-failure:3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    restart: on-failure:3


